services:
  api:
    image: meufinanceiro-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5009:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=meufinanceiro_db;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: meufinanceiro-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meufinanceiro_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: